---
title: "Indirect Interventions for Stabilizing Housing Markets"
subtitle: "Reproduction of Unemployment Insurance as a Housing Market Stabilizer (Hsu, Matsa, and Melzer 2018)"
author: 
  - Roy Chan
thanks: "Code and data are available at: https://github.com/chan-roy/HousingMarkets"
date: "`r format(Sys.time(), '%d %B %Y')`"
abstract: "Preventing home foreclosures due to their associated costs is a key concern for policymakers during periods of economic instability. (Hsu, Matsa, and Melzer 2018) investigate the impact of unemployment insurance (UI) to stabilize the housing market, evaluating that UI expansions during the Great Recession aided in preventing foreclosures and stabilized home values. This paper replicates the analysis of their study and investigates alternative factors that impacted foreclosure rates and home valuation. \\textbf{Keywords:} housing market stability, personal finance, great recession, unemployment insurance, foreclosures, economic policy, united states"
output:
  bookdown::pdf_document2
toc: FALSE
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

# Introduction

During periods of severe housing market instability such as the time of the Great Recession, policymakers are concerned with the potential of bearing the associated costs of defaulted mortgages and foreclosures. However, it is not always clear what type of intervention is most appropriate and/or feasible to relieve this issue provided the likelihood of high strain on the economy during such times. In the paper \textit{Unemployment Insurance as a Housing Market Stabilizer} [@citeHsu], it is discussed that there exists a debate on the reasoning for mortgage defaults rendering it difficult to effectively design an intervening policy.

In this paper, we will be replicating the analysis originally presented by [@citeHsu] as well as expanding on additional indirect factors mentioned but not thoroughly explored in the original paper.

# Data
[@citeR]

# Model

# Results

# Discussion

\newpage

\appendix

# Appendix {-}

# Enhancement

\newpage

# References


